language: python
python:
  - "3.7"
  - "3.4"
env:
  - DJANGO=3.1.4 DB=sqlite3
  -
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - coverage run --source=memories manage.py test
