language: python
# todo fix build script
python:
  - "3.7"

env:
  global:
    - SECRET_KEY='MY_SECRET_KEY'
    - DJANGO=3.1.4
    - PUBLIC_KEY=RECAPTCHA_PUBLIC_KEY
    - PRIVATE_KEY=RECAPTCHA_PRIVATE_KEY
    - DB_NAME='test_db'
    - DB_USER='postgres'
    - DB_PASSWORD=''
    - DB_HOST='localhost'

services:
  - postgresql

before_script:
  - psql -c 'CREATE DATABASE test_db;' -U travis

#after_script:
#  - psql -c '\c test_db;'
#  - psql -c 'CREATE INDEX test_gin_index ON memories_place USING GIN (to_tsvector('english', name));'

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - python manage.py makemigrations memories
  - python manage.py migrate
  - coverage run --source=memories manage.py test

after_success:
  coveralls