language: python
# todo fix build script
python:
  - "3.7"

env:
  global:
    - repo_token=token
    - SECRET_KEY='MY_SECRET_KEY'
    - DJANGO=3.1.4
    - EMAIL_HOST=EMAIL_HOST
    - EMAIL_HOST_USER=EMAIL_HOST_USER
    - EMAIL_HOST_PASSWORD=EMAIL_HOST_PASSWORD
    - DEFAULT_FROM_EMAIL=DEFAULT_FROM_EMAIL
    - PUBLIC_KEY=RECAPTCHA_PUBLIC_KEY
    - PRIVATE_KEY=RECAPTCHA_PRIVATE_KEY
    - DB_NAME='test_db'
    - DB_USER='postgres'
    - DB_PASSWORD=''
    - DB_HOST='localhost'

services:
  - postgresql

before_script:
  - psql -c 'CREATE DATABASE test_db;' -U postgres

after_script:
  - psql -c 'CREATE INDEX test_gin_index ON test_db.public.memories_place USING gin(name);'

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - python manage.py makemigrations memories
  - python manage.py migrate

after_success:
  coveralls