language: python

python:
  - "3.7"

env:
  - SECRET_KEY='MY_SECRET_KEY'
  - DJANGO=3.1.4 DB=sqlite3
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - python manage.py makmigrations
  - python manage.py migrate
  - python manage.py test
