# This is a basic workflow to help you get started with Actions

name: CI
env:
  EMAIL_HOST: 'some.smtp.host'
  EMAIL_HOST_USER: 'some.user'
  EMAIL_HOST_PASSWORD: 'some.user.password'
  DEFAULT_FROM_EMAIL: 'some@mail.com'

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2


      # Runs a set of commands using the runners shell
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run manage.py makemigrations
        run: python manage.py makemigrations

      - name: Run manage.py migrate
        run: python manage.py migrate

      - name: Run tests
        run: python manage.py test
          
          
          
